switch (sessionStorage.theme) {
case 'Food':
	var questions = [
		'What time do you usually have breakfast ?',
		'What time do you usually have lunch ?',
		'What time do you usually have dinner ?',
		'What do you usually have for breakfast ?',
		'What did you have for lunch yesterday ?',
		'What did you have for dinner yesterday ?',
		'What did you have for lunch today ?',
		'What will you have for dinner today ?',
		'Have you ever tried Chinese food ?',
		'Have you ever tried Indian food ?',
		'Have you ever tried Mexican food ?',
		'Do you like Italian food ?',
		'Do you like fruits and vegetables ?',
		'Do you like trying new foods ?',
		'Do you have any food allergies ?',
		'Which are your favourite desserts ?',
		'Which are your favourite drinks ?',
		'Which is your favourite meat ?',
		'Which is your favourite ice-cream flavour ?',
		'How often do you eat Take-away food ?',
		'How often do you eat at a restaurant ?',
		'Which are your favourite restaurants ?',
		'Are there any foods you hate ?',
		'How many healthy foods can you think of ?',
		'How many unhealthy foods can you think of ?',
		'How many pizza toppings can you think of ?',
		'How many hamburger ingredients can you think of ?',
		'How many vegetables can you name ?',
		'How many fruits can you name ?',
		'What foods do people eat at Birthday parties ?',
		'What foods do people eat at Christmas time ?',
		'What foods do people eat at the cinema ?',
		'What is cheese made of ?',
		'What is yoghurt made of ?',
		'Where do apples grow ?',
		'What do rabbits eat ?'
	];
	break;
	
case 'Space':
	var questions = [
		'Which travels faster: light or sound ?',
		'How long does light take to travel from the Sun to Earth ?<br><br>8 minutes - 10 minutes - 12 minutes',
		'We always see the same side of the Moon. True or false ?',
		'How many people have walked on the moon ?<br><br>six - twelve - eighteen',
		'When was the first satellite launched into space ?<br><br>1947 - 1957 - 1967',
		'The Sun is a star. True or false ?',
		'Name the biggest planet in our Solar System.',
		'Which is the second biggest planet in the Solar System',
		'Which is the closest planet to the Sun ?<br><br>Venus - Mercury - Mars',
		'Which is the furthest planet from the Sun ?<br><br>Uranus - Saturn - Neptune',
		'How long does it take the Moon to orbit the Earth ?<br><br>A year - 28 days - A day',
		'How long does it take Earth to rotate on its axis ?<br><br>24 hours - A month - A year',
		'How long does it take Earth to orbit the Sun ?<br><br>24 hours - A month - A year',
		'Order these planets from smallest to biggest:<br><br>Earth - Jupiter - Mercury',
		'Why are the planets Mercury and Venus hotter than Earth ?',
		'Which is not a planet ? The Earth or the Moon ?',
		'On which planet is the biggest volcano in the Solar System ?<br><br>Jupiter - Earth - Mars',
		'How many moons does Mars have ?<br><br>one - two - three',
		'Who was the first person to walk on the Moon ?',
		'Who was the first person to go into space ?',
		'Which planet is known as the red planet ?',
		'What is the name of NASA’s most famous space telescope ?',
		'Is the planet Neptune bigger than Earth ?',
		'What is the distance from the Earth to the Sun ?<br><br>50 million km - 100 million km - 150 million km',
		'Which is the fifth planet from the Sun ?<br><br>Jupiter - Saturn - Neptune',
		'How many planets are in our Solar System ?',
		'What are the rings around Saturn made of ?<br><br>Ice and Rock - Gas - Gold and Silver',
		'When was Pluto discovered ?<br><br>1870 - 1900 - 1930',
		'How many Earths could fit inside the Sun ?<br><br>1 million - 10 million - 100 million',
		'Which planet is sometimes called Earth\'s sister Planet ?<br><br>Venus - Mars - Mercury',
		'How many planets in the solar system are made of gas ?<br><br>Two - Three - Four',
		'In which year was the first chimpanzee sent into space ?<br><br>1959 - 1960 - 1961'
	];
	break;
	
case 'Sport':
	var questions = [
		'Which sports do you like to practice ?',
		'Do you play in any sports teams ?',
		'Do you like to watch sports ? Which ones ?',
		'Have you ever played crazy golf ?',
		'Do you practice any snow sports ?',
		'Have you ever watched a sport at a sports stadium ?',
		'Do you think everybody should practice sports ? Why ?',
		'Do you do sports with your family ?',
		'Have you ever done surfing or bodyboarding ?',
		'Which do you think are the most popular sports in your country ?',
		'Which sports are the most dangerous ?',
		'Which sports are the most expensive to do ?',
		'Who is your favourite sportsperson ? Why ?',
		'Which new sports would you like to try ?',
		'Are there any sports that you don\'t like ?',
		'How often do you watch sports on TV ?',
		'When did you learn how to swim ?',
		'In which sports do you use a bat ?',
		'In which sports do you use a racket ?',
		'How often do the Olympic games take place ?',
		'What colours are the medals for first, second and third place ?',
		'In which sports do you NOT use a ball ?',
		'How long is each half in a game of football ?',
		'Which country has won the football World Cup most times ?',
		'Where was the last football World Cup held ?',
		'Which country won the last football World Cup ?',
		'Have you ever done ten pin bowling ?',
		'Who is the fastest person in the world ?',
		'Which athlete has won most medals in the Olympic games ?',
		'Which player has won most titles in Tennis ?',
		'Who is the only player allowed to touch the ball with their hands in football ?',
		'How many rings does the Olympic flag have ?',
		'Have you ever competed in any sports competitions ?',
		'Which sportspeople would you like to meet ?',
		'Who are the most famous sportspeople in your country ?',
		'Have you ever played tennis ?'
	];
	break;
	
case 'Halloween':
	var questions = [
		'What is the date of Halloween ?',
		'How do you celebrate Halloween ?',
		'Do you like to go Trick-or-Treating ?',
		'What wouldn\'t you like to get if you went Trick-or-Treating ?',
		'What "Fancy dress costumes" do people wear at Halloween ?',
		'Do you usually wear a "Fancy dress costume" at Halloween ?',
		'Which is the best "Fancy dress costume" you remember seeing ?',
		'Which is the worst "Fancy dress costume" you remember seeing ?',
		'What is the difference between the words "Witch" and "Which" ?',
		'How old is too old to go Trick-or-Treating ?',
		'Which colours are associated with Halloween and why ?',
		'Do you like watching scary movies ?',
		'Do you know any Halloween games ?',
		'What food do people eat at a Halloween party ?',
		'Have you ever ridden a Ghost Train ?',
		'Have you ever entered a Haunted House ?',
		'Do you like to "play tricks" on people at Halloween ?',
		'Have you ever eaten Pumpkin ?',
		'Do you decorate your house at Halloween ?',
		'How many Halloween "monsters" can you think of ?',
		'Do you believe in ghosts ?',
		'What would you do if you saw a ghost ?',
		'Do you make a Jack-o\'-Lantern at Halloween ?',
		'Do you prefer friendly or scary Jack-o\'-Lanterns ? Why ?',
		'What is the most scared you have ever been ?',
		'Are you afraid of spiders ?',
		'Have you ever seen a bat in "real life" ?',
		'Do you know anything about the history of Halloween ?',
		'Who would you like to "Haunt" if you could ?',
		'Which Halloween monster would you like to be if you could ?',
		'Would you like to live forever as a Vampire ?',
		'Would you like to "cast spells" on people like a Witch ?',
		'Do you do any activities at school for Halloween ?',
		'Which animal is a witch\'s best friend ?'
	];
	break;
	
case 'Christmas':
	var questions = [
		'Where does Santa Claus live ?',
		'On which day is Christmas day ?',
		'Which colours are associated with Christmas ?',
		'Do you know the history of Christmas ?',
		'What foods do people eat at Christmas ?',
		'Which is your favourite Chistmas food ?',
		'Are there any Christmas foods you don\'t like ?',
		'What was the original colour of Father Christmas ?',
		'What activities do you like to do at Christmas time ?',
		'Which was your best present last year ?',
		'What do you want for Christmas this year ?',
		'Do you know what presents you are getting this year ?',
		'Have you ever gotten a present you didn\'t like ?',
		'What time do you normally open your presents ?',
		'Do you get presents for your pets ?',
		'Do you have a photo of you with Santa Claus ?',
		'Did you write a letter to Santa this year ?',
		'When do you normally put your Christmas decorations up ?',
		'Do you normally hang up a Christmas stocking ?',
		'Do you normally write Christmas cards for friends and family ?',
		'Which do you prefer, Santa Claus or the Three Wise Men ?',
		'Do you prefer Christmas time or your Birthday ?',
		'How many Christmas songs can you name ?',
		'How many Christmas films can you name ?',		
		'Do you normally travel at Christmas time ?',
		'Do your relatives normally visit you at Christmas time ?',
		'Do you normally have a Christmas Party ?',
		'Did you do any Christmas activities at school this year ?',
		'How long are you off school for Christmas ?',
		'When was the last time you made a snowman ?',
		'When was the last time you had a snowball fight ?',
		'What were the best things that happened to you this year ?',
		'How many of Santa\'s reindeer do you know the names of ?'
	];
	break;
	
case 'Clothes':
	var questions = [
		'What are you wearing today ?',
		'What did you wear yesterday ?',
		'Which are your favourite clothes ?',
		'When was the last time you dropped food on your clothes ?',
		'Do you have a favourite style of clothes ?',
		'How often do you go shopping for clothes ?',
		'Do you like the latest fashions ?',
		'What clothes are in fashion now ?',
		'Are there any types of clothes you don\'t like ?',
		'What clothes do people wear at the beach ?',
		'What clothes do people wear in Winter ?',
		'Have you ever worn ripped clothes ?',
		'Do you buy clothes online ?',
		'Have you ever bought clothes that you didn\'t wear ?',
		'Have you ever bought clothes as a present for someone ?',
		'Do you like getting clothes as a present ?',
		'What is the best type of clothing to receive as a present ?',
		'What is the worst type of clothing to receive as a present ?',
		'What do you think about wearing leather and fur ?',
		'What do you think about clothes from other countries ?',
		'Do you prefer Summer or Winter clothes ?',
		'Do you prefer sports clothes or smart clothes ?',
		'Do you prefer velcro or laces on your shoes ?',
		'Do you have a favourite clothes colour ?',
		'Do you have a favourite shop for buying clothes ?',
		'What is the oldest item of clothing you have ?',
		'What is the newest item of clothing you have ?',
		'Do you have a Christmas jumper ?',
		'Do you have socks with pictures on them ?',
		'Do you have a tracksuit ?',
		'Do you have traditional clothes from your country ?',
		'How many hats do you have ?',
		'How many pairs of shoes do you have ?',
		'Do you have many clothes you don\'t use ?',
		'What item of clothing do you have most of ?',
		'Do you recycle clothes ?',
		'How many different types of footwear can you think of ?',
		'Which clothes have buttons ?',
		'Which clothes have zips ?',
		'Which clothes have sleeves ?',
		'Which clothes come in pairs ?',
		'What is you shoe size ?'
	];
	break;
	
case 'Animals':
	var questions = [
		'Which is your favourite animal and why ?',
		'Have you seen your favourite animal in real life ?',
		'Are there any animals you are scared of ?',
		'Are there any animals that disgust you ?',
		'Do you have any pets ?',
		'What was the name of your first pet ?',
		'Do you have any friends who have unusual pets ?',
		'When was the last time you visited a pet shop ?',
		'How many animals can you name in 30 seconds ?',
		'Can you name ten mammals ?',
		'Can you name three birds ?',
		'Can you name three reptiles ?',
		'Can you name any animals in danger of extinction ?',
		'How many animal species are there ?',
		'Which is the fastest land animal ?',
		'Which is the fastest bird ?',
		'Which the fastest animal in water ?',
		'Which is the heaviest living animal ?',
		'Which animal has the most teeth ?',
		'Which animal has the most powerful bite ?',
		'Which animal is the most venomous ?',
		'Which is the longest living animal ?',
		'Which animal has lived on earth for the longest time ?',
		'How many years did the oldest tortoise live for ?',
		'Which are the most dangerous animals ?',
		'Which continent has the most animals ?',
		'What are some common animals that live in your country ?',
		'In which different habitats do animals live ?',
		'Have you ever taught a dog any tricks ?',
		'Have you ever been attacked by an animal ?',
		'Have you ever ridden a horse ?',
		'Have you ever visited a zoo ?',
		'Have you ever been bird watching ?',
		'Have you ever seen animals racing ?',
		'Do you like eating fish ?',
		'Can you do any animal impressions ?',
		'If you could be any animal for a day, which would you be ?',
		'If you could talk with animals, what would you ask them ?',
		'Do you think that animals dream ?',
		'Should animals be kept in zoos ?'
	];
	break;
	
}
